### ISSUE TITLE
Count cyclomatic complexity of 5 functions by hand

### ISSUE THREAD

**Issue by lovisastrange** [eloidieme/DD2480_Coverage#7]
Count the cyclomatic complexity of five large functions in the code (not necessarily the largest ones, in case you cannot sort them automatically by size). Exclude third-party code and generated code in this. Next, count the cyclomatic complexity of these five complex functions by hand.

Note: Use at least two group members to count the complexity separately, to get a reliable results. Use a third member if the two counts differ.

1. What are your results? Did everyone get the same result? Is there something that is unclear? If you have a tool, is its result the same as yours?

2. Are the functions/methods with high CC also very long in terms of LOC?

3. What is the purpose of these functions? Is it related to the high CC?

4. If your programming language uses exceptions: Are they taken into account by the tool? If you think of an exception as another possible branch (to the catch block or the end of the function), how is the CC affected?

5. Is the documentation of the function clear about the different possible outcomes induced by different branches taken?

**Comment by eloidieme** [comment]
[notes_complexité_cyclomatique.pdf](https://github.com/eloidieme/DD2480_Coverage/files/14352148/notes_complexite_cyclomatique.pdf)

**Comment by lovisastrange** [comment]
[Count_of_cyclomatic_complexity.pdf](https://github.com/eloidieme/DD2480_Coverage/files/14356835/Count_of_cyclomatic_complexity.pdf)
